package repo

import (
	"context"
	"time"

	"github.com/ILITA-hub/animeenigma/services/player/internal/domain"
	"gorm.io/gorm"
)

// RecEventsRepository persists RecEvent rows for the eval pipeline.
// Phase 14 (REC-EVAL-01). Single-method append-only API — analytics
// reads happen via direct SQL against the rec_events table for v2.1
// weight-tuning workflows; this repo exists only for the write path.
type RecEventsRepository struct {
	db *gorm.DB
}

// NewRecEventsRepository wires the repository with the player DB handle.
func NewRecEventsRepository(db *gorm.DB) *RecEventsRepository {
	return &RecEventsRepository{db: db}
}

// Insert appends one rec_events row. Auto-fills CreatedAt with time.Now().UTC()
// when zero. The ID column is auto-generated by Postgres via gen_random_uuid()
// (or sqlite via the GORM default at test time).
func (r *RecEventsRepository) Insert(ctx context.Context, ev *domain.RecEvent) error {
	if ev.CreatedAt.IsZero() {
		ev.CreatedAt = time.Now().UTC()
	}
	return r.db.WithContext(ctx).Create(ev).Error
}
