apiVersion: 1

contactPoints:
  - orgId: 1
    name: telegram-alerts
    receivers:
      - uid: telegram-alerts
        type: telegram
        settings:
          bottoken: $__env{TELEGRAM_ALERTS_BOT_TOKEN}
          chatid: $__env{TELEGRAM_ADMIN_CHAT_ID}
          parse_mode: HTML
          message: |
            {{ if eq .Status "firing" }}🔴{{ else }}🟢{{ end }} <b>{{ .Status | title }}</b>
            {{ range .Alerts }}
            <b>{{ .Labels.alertname }}</b>
            {{ .Annotations.summary }}
            {{ .Annotations.description }}
            {{ end }}
        disableResolveMessage: false
