apiVersion: 1

contactPoints:
  - orgId: 1
    name: maintenance-webhook
    receivers:
      - uid: maintenance-webhook
        type: webhook
        settings:
          url: "http://host-gateway:8087/api/grafana-webhook"
          httpMethod: "POST"
          username: "grafana"
          password: "WEBHOOKPASS_PLACEHOLDER"
